# Generated by Django 4.0.5 on 2022-06-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_alter_book_image_alter_book_isbn_alter_book_isbn13_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
