# Generated by Django 4.0.5 on 2022-06-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0005_alter_author_name_alter_book_authors_alter_book_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='goodreads_id',
        ),
    ]
