# Generated by Django 4.0.5 on 2022-06-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0007_remove_book_goodreads_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn13',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
