# Generated by Django 4.0.5 on 2022-07-01 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0008_alter_book_isbn_alter_book_isbn13'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='goodreads_id',
        ),
    ]
